export default [
	{
		id: 1,
		name: 'Тестовое наименование',
		href: '#',
		imageSrc: '/images/category/sample_1.webp',
		imageAlt: "Front of men's Basic Tee in black.",
		images: [
			'/images/category/sample_2.webp',
			'/images/category/sample_3.webp',
			'/images/category/sample_1.webp',
			'/images/category/sample_2.webp',
			'/images/category/sample_3.webp',
			'/images/category/sample_4.webp',
		],
		price: '350 руб / шт',
		color: 'Черный',
		categoryId: 1,
		description:
			'Эта футболка с классическим кроем и мягким материалом идеально подходит для повседневной носки. Она станет универсальной базой для вашего гардероба, позволяя сочетать её с любыми вещами.',
	},
	{
		id: 2,
		name: 'Тестовое наименование 2',
		href: '#',
		imageSrc: '/images/category/sample_2.webp',
		imageAlt: "Front of men's Basic Tee in black.",
		images: [
			'/images/category/sample_2.webp',
			'/images/category/sample_4.webp',
		],
		price: '350 руб / шт',
		color: 'Черный',
		categoryId: 1,
		description:
			'Стильная футболка, которая привлекает внимание своим минималистичным дизайном. Элегантно подчеркивает фигуру, она отлично подойдет как для повседневной носки, так и для выходов в город.',
	},
	{
		id: 3,
		name: 'Тестовое наименование 3',
		href: '#',
		imageSrc: '/images/category/sample_3.webp',
		imageAlt: "Front of men's Basic Tee in black.",
		images: [
			'/images/category/sample_3.webp',
			'/images/category/sample_2.webp',
			'/images/category/sample_1.webp',
			'/images/category/sample_4.webp',
		],
		price: '350 руб / шт',
		color: 'Черный',
		categoryId: 1,
		description:
			'Эта футболка выделяется своим уникальным дизайном и удобной посадкой, что делает её идеальным выбором для активных дней. С ней вы всегда будете выглядеть стильно и привлекательно.',
	},
	{
		id: 4,
		name: 'Тестовое 4',
		href: '#',
		imageSrc: '/images/category/sample_4.webp',
		imageAlt: "Front of men's Basic Tee in black.",
		images: [
			'/images/category/sample_2.webp',
			'/images/category/sample_3.webp',
			'/images/category/sample_1.webp',
			'/images/category/sample_2.webp',
			'/images/category/sample_3.webp',
			'/images/category/sample_2.webp',
			'/images/category/sample_3.webp',
			'/images/category/sample_4.webp',
		],
		price: '35 руб / шт',
		color: 'Зеленый',
		categoryId: 2,
		description:
			'Этот яркий и стильный топ станет отличным дополнением к вашему гардеробу. Он идеально подходит для летних прогулок и вечеринок, добавляя красок и настроения в ваш образ.',
	},
	{
		id: 5,
		name: 'Тестовое наименование 5',
		href: '#',
		imageSrc: '/images/category/sample_2.webp',
		imageAlt: "Front of men's Basic Tee in black.",
		images: ['/images/category/sample_2.webp'],
		price: '350 руб / шт',
		color: 'Черный',
		categoryId: 2,
		description:
			'Эта базовая футболка — незаменимая вещь для любого мужчины. Простота и комфорт делают её идеальным выбором для повседневного использования.',
	},
	{
		id: 6,
		name: 'Тестовое наименование 6',
		href: '#',
		imageSrc: '/images/category/sample_3.webp',
		imageAlt: "Front of men's Basic Tee in black.",
		images: [
			'/images/category/sample_2.webp',
			'/images/category/sample_3.webp',
		],
		price: '350 руб / шт',
		color: 'Черный',
		categoryId: 2,
		description:
			'Эта футболка сочетает в себе стиль и функциональность. Она идеально подходит для спортивных мероприятий и активного отдыха. Наденьте её с шортами или джинсами для создания непринужденного образа.',
	},
	{
		id: 7,
		name: 'Тестовое 4',
		href: '#',
		imageSrc: '/images/category/sample_4.webp',
		imageAlt: "Front of men's Basic Tee in black.",
		images: [
			'/images/category/sample_4.webp',
			'/images/category/sample_4.webp',
			'/images/category/sample_4.webp',
		],
		price: '35 руб / шт',
		color: 'Зеленый',
		categoryId: 3,
		description:
			'Эта футболка с ярким цветом и интересным дизайном идеально подойдет для тех, кто любит выделяться. Отличный выбор для летнего сезона и активного отдыха.',
	},
	{
		id: 8,
		name: 'Тестовое наименование 7',
		href: '#',
		imageSrc: '/images/category/sample_1.webp',
		imageAlt: "Front of men's Basic Tee in black.",
		images: [
			'/images/category/sample_1.webp',
			'/images/category/sample_2.webp',
			'/images/category/sample_3.webp',
		],
		price: '400 руб / шт',
		color: 'Синий',
		categoryId: 3,
		description:
			'Современная футболка с уникальным принтом, идеально подходящая для молодежного стиля. Она отлично смотрится как с джинсами, так и с шортами.',
	},
	{
		id: 9,
		name: 'Тестовое наименование 8',
		href: '#',
		imageSrc: '/images/category/sample_2.webp',
		imageAlt: "Front of men's Basic Tee in black.",
		images: [
			'/images/category/sample_2.webp',
			'/images/category/sample_4.webp',
		],
		price: '450 руб / шт',
		color: 'Красный',
		categoryId: 1,
		description:
			'Эта яркая футболка станет акцентом вашего образа. Она идеально подходит для летних прогулок и вечеринок, подчеркивая вашу индивидуальность.',
	},
];
